// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user_service/rpc_signin.proto

package user_service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SigninRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SigninRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SigninRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SigninRequestMultiError, or
// nil if none found.
func (m *SigninRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SigninRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Password

	if len(errors) > 0 {
		return SigninRequestMultiError(errors)
	}

	return nil
}

// SigninRequestMultiError is an error wrapping multiple validation errors
// returned by SigninRequest.ValidateAll() if the designated constraints
// aren't met.
type SigninRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SigninRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SigninRequestMultiError) AllErrors() []error { return m }

// SigninRequestValidationError is the validation error returned by
// SigninRequest.Validate if the designated constraints aren't met.
type SigninRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SigninRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SigninRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SigninRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SigninRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SigninRequestValidationError) ErrorName() string { return "SigninRequestValidationError" }

// Error satisfies the builtin error interface
func (e SigninRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSigninRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SigninRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SigninRequestValidationError{}

// Validate checks the field values on SigninResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SigninResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SigninResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SigninResponseMultiError,
// or nil if none found.
func (m *SigninResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SigninResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SigninResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SigninResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SigninResponseValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SessionId

	// no validation rules for AccessToken

	// no validation rules for RefreshToken

	if all {
		switch v := interface{}(m.GetAccessTokenExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SigninResponseValidationError{
					field:  "AccessTokenExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SigninResponseValidationError{
					field:  "AccessTokenExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccessTokenExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SigninResponseValidationError{
				field:  "AccessTokenExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRefreshTokenExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SigninResponseValidationError{
					field:  "RefreshTokenExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SigninResponseValidationError{
					field:  "RefreshTokenExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRefreshTokenExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SigninResponseValidationError{
				field:  "RefreshTokenExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SigninResponseMultiError(errors)
	}

	return nil
}

// SigninResponseMultiError is an error wrapping multiple validation errors
// returned by SigninResponse.ValidateAll() if the designated constraints
// aren't met.
type SigninResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SigninResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SigninResponseMultiError) AllErrors() []error { return m }

// SigninResponseValidationError is the validation error returned by
// SigninResponse.Validate if the designated constraints aren't met.
type SigninResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SigninResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SigninResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SigninResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SigninResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SigninResponseValidationError) ErrorName() string { return "SigninResponseValidationError" }

// Error satisfies the builtin error interface
func (e SigninResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSigninResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SigninResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SigninResponseValidationError{}
